# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sample-ds-project-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_d8f384bd63ca489698414f3ee2f9d7b2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d35c38efed184473a52f3c4b16ed1f57 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d8f384bd63ca489698414f3ee2f9d7b2 }}/deepak93p/sample-ds-project:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sample-ds-project-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9a36e93f19654f13992bc9d1d3810da9 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d8f384bd63ca489698414f3ee2f9d7b2 }}/deepak93p/sample-ds-project:${{ github.sha }}'